on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out the repository.
        uses: actions/checkout@v2
      - name: Compile the application.
        run: make build