on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out the repository.
        uses: actions/checkout@v2
      - name: Compile the application.
        run: make build
      - name: Rename macos binary.
        run: mv no-blank no-blank-macos
      - name: Release macos binary.
        uses: softprops/action-gh-release@v1
        with:
          body: MacOS binary
          files: no-blank-macos