on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out the repository.
        uses: actions/checkout@v2
      - name: Compile the application.
        run: make build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: no-blank
          commit_message: Add binary for macos.