on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository.
        uses: actions/checkout@v2
      - name: Compile the application.
        run: make build