on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out the repository.
        uses: actions/checkout@v2
      - name: Compile the application.
        run: make build
      - name: Release windows binary.
        uses: softprops/action-gh-release@v1
        with:
          body: Windows binary
          files: no-blank.exe